---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Create group
  group:
    name: "{{ synapse_group }}"
    state: present

- name: Create user
  user:
    name: "{{ synapse_user }}"
    group: "{{ synapse_group }}"
    create_home: yes
    home: "{{ synapse_venv_path }}"

- name: Create required folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ synapse_user }}"
    group: "{{ synapse_group }}"
  with_items:
    - "{{ synapse_config_path }}"
    - "{{ synapse_config_path }}/conf.d"
    - "{{ synapse_data_directory }}"
    - "{{ synapse_media_store_path }}"

- name: Make sure synapse is installed to the VEnv
  pip:
    name:
      - pip
      - setuptools
      - "matrix-synapse[all]=={{ synapse_pip_version }}"
    virtualenv: "{{ synapse_venv_path }}"
    virtualenv_command: /usr/bin/python3 -m venv
    extra_args: --upgrade
  notify: restart synapse
  become: yes
  become_user: "{{ synapse_user }}"

- name: Generate secrets and first config-file
  command: "{{ synapse_venv_path }}/bin/python -m synapse.app.homeserver --server-name {{ synapse_domain }} --config-path={{ synapse_config_path }}/homeserver.yaml --generate-config --report-stats=no"
  when: not (synapse_registration_shared_secret is defined and synapse_registration_shared_secret != "")

- name: Notify users about secrets
  fail:
    msg: "Secrect and keys were generated for you. See the README.md (-> Secrets) for further details"
  when: not (synapse_registration_shared_secret is defined and synapse_registration_shared_secret != "")

- name: Add signing key
  copy:
    dest: "{{ synapse_config_path }}/{{ synapse_domain }}.signing.key"
    content: "{{ synapse_signing_key }}"
    owner: "{{ synapse_user }}"
    group: "{{ synapse_group }}"
    mode: "0440"
  when: synapse_registration_shared_secret is defined and synapse_registration_shared_secret != ""

- name: Add homeserver config
  template:
    src: "homeserver.yaml.j2"
    dest: "{{ synapse_config_path }}/homeserver.yaml"
    owner: "{{ synapse_user }}"
    group: "{{ synapse_group }}"
    mode: "0440"
  notify: restart synapse
  when: synapse_registration_shared_secret is defined and synapse_registration_shared_secret != ""

- name: Add log config
  template:
    src: "synapse.log.config.j2"
    dest: "{{ synapse_config_path }}/{{ synapse_domain }}.log.config"
    owner: "{{ synapse_user }}"
    group: "{{ synapse_group }}"
    mode: "0440"
  notify: restart synapse

- name: Upload systemd service file
  template:
    src: "systemd/matrix-synapse.service.j2"
    dest: "/etc/systemd/system/{{ synapse_systemd_service_name }}.service"

- name: Upload service defaults
  template:
    src: "env-synapse.j2"
    dest: "/etc/default/matrix-synapse"
  notify: restart synapse

- name: Make sure synapse systemd-service is enabled and running
  service:
    name: "matrix-synapse"
    state: started
    enabled: yes
    daemon-reload: yes
